### PR TITLE
Add Script tag with AMF3 content.

### PR DESCRIPTION
**Pull request by byronclark**
This doesn't parse the tag, but it at least recognizes it in the stream
and continues on. Wikipedia calls this the RTMP Stream Flex Send tag
while the RTMP docs call it a data tag containing AMF3.

### CODE REVIEW

**Comment by byronclark** [comment]
I've only seen this in files generated by Adobe Media Server where the client sends objects on the NetStream.

**Comment by wulczer** [comment]
Hey, thanks a bunch for the pull request! A few minor points:
- no need to override the superclass's constructor, just don't define `__init__` in `ScriptAmf3Tag`
- while at it, could you call the class `ScriptAMF3Tag` ? I somehow prefer that way of writing camel case...
- it would be great if you could add a really simple test in `test/test_tags.py` (or I can handle it myself after merging)

Care to reopen the pull request with the above changes?

**Comment by wulczer** [comment]
Oh, one other tiny little thing: could you maintain the order of entries in the `tag_to_class` dict? Thanks!

**Comment by byronclark** [comment]
Thanks for the feedback. New commit pushed that should address all your comments.

**Comment by wulczer** [comment]
Swell, thanks a lot! I'm going to fix a failing unit test and put a new release on PyPI.

**Comment by wulczer** [comment]
Released 0.1.13 on PyPI.

**Pull request merged**
